import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialBaseline1775641990967 implements MigrationInterface {
    name = 'InitialBaseline1775641990967'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "warehouses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "code" character varying NOT NULL, "is_default" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_56ae21ee2432b2270b48867e4be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "resource" character varying NOT NULL, "action" character varying NOT NULL, "code" character varying NOT NULL, CONSTRAINT "UQ_8dad765629e83229da6feda1c1d" UNIQUE ("code"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password_hash" character varying NOT NULL, "name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" character varying(64) NOT NULL, "title" character varying(255) NOT NULL, "body" text, "read_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_569622b0fd6e6ab3661de985a2b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "units_of_measure" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ce93a9c86be10704b5415ca4bee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "areas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_5110493f6342f34c978c084d0d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "towns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "area_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_8f5c3dbce1d3ea5de7dcc48c230" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tax_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "rate" numeric(7,4) NOT NULL DEFAULT '0', "is_inclusive" boolean NOT NULL DEFAULT false, "region" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ef858dd4bea5263571888920b64" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment_terms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "net_days" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a7e7ab8cabd8982c57d817b7164" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "suppliers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "contact" jsonb, "payment_terms_id" uuid, "tax_profile_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_b70ac51766a9e3144f778cfe81e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "parent_id" uuid, "name" character varying NOT NULL, "code" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_7069dac60d88408eca56fdc9e0c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "price_levels" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4760462e69751c4a842658885e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_prices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "price_level_id" uuid NOT NULL, "price" numeric(14,4) NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_31c33ddacf759f7c0e5d327c4bb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "supplier_id" uuid NOT NULL, "category_id" uuid NOT NULL, "sku" character varying NOT NULL, "barcode" character varying, "name" character varying NOT NULL, "unit_id" uuid NOT NULL, "cost_price" numeric(14,4) NOT NULL DEFAULT '0', "selling_price" numeric(14,4) NOT NULL DEFAULT '0', "batch_tracked" boolean NOT NULL DEFAULT false, "expiry_tracked" boolean NOT NULL DEFAULT false, "costing_method" character varying(8), "min_stock" numeric(14,4), "reorder_level" numeric(14,4), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_order_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchase_order_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity" numeric(14,4) NOT NULL, "unit_price" numeric(14,4) NOT NULL, "tax_amount" numeric(14,4) NOT NULL DEFAULT '0', "discount_amount" numeric(14,4) NOT NULL DEFAULT '0', "received_quantity" numeric(14,4) NOT NULL DEFAULT '0', "tax_profile_id" uuid, CONSTRAINT "PK_34a2082d2abb10c5d8713bc19b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "supplier_id" uuid NOT NULL, "order_date" date NOT NULL, "expected_date" date, "status" character varying NOT NULL DEFAULT 'draft', "warehouse_id" uuid NOT NULL, "subtotal" numeric(14,4) NOT NULL DEFAULT '0', "tax_amount" numeric(14,4) NOT NULL DEFAULT '0', "discount_amount" numeric(14,4) NOT NULL DEFAULT '0', "total" numeric(14,4) NOT NULL DEFAULT '0', "notes" text, "created_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_05148947415204a897e8beb2553" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d16a885aa88447ccfd010e739b" ON "purchase_orders" ("supplier_id") `);
        await queryRunner.query(`CREATE TABLE "grn_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "grn_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity" numeric(14,4) NOT NULL, "unit_price" numeric(14,4) NOT NULL DEFAULT '0', "batch_code" character varying(128), "expiry_date" date, "purchase_order_line_id" uuid, CONSTRAINT "PK_9716c2ffa1be55de5558fccd5a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "grns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "purchase_order_id" uuid, "supplier_id" uuid NOT NULL, "grn_date" date NOT NULL, "warehouse_id" uuid NOT NULL, "status" character varying NOT NULL DEFAULT 'draft', "created_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_eef22b363aa66336dca8a5ce961" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b8948b78af50773643eae7bc20" ON "grns" ("purchase_order_id") `);
        await queryRunner.query(`CREATE TABLE "supplier_invoice_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "supplier_invoice_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity" numeric(14,4) NOT NULL, "unit_price" numeric(14,4) NOT NULL, "tax_amount" numeric(14,4) NOT NULL DEFAULT '0', "discount_amount" numeric(14,4) NOT NULL DEFAULT '0', "grn_line_id" uuid, "tax_profile_id" uuid, CONSTRAINT "PK_c7b04c7978d9b9fb4cf4c0b9ab5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "supplier_invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "supplier_id" uuid NOT NULL, "invoice_number" character varying NOT NULL, "invoice_date" date NOT NULL, "due_date" date NOT NULL, "purchase_order_id" uuid, "grn_id" uuid, "status" character varying NOT NULL DEFAULT 'draft', "subtotal" numeric(14,4) NOT NULL DEFAULT '0', "tax_amount" numeric(14,4) NOT NULL DEFAULT '0', "discount_amount" numeric(14,4) NOT NULL DEFAULT '0', "total" numeric(14,4) NOT NULL DEFAULT '0', "notes" text, "created_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_08f98a1a117d65ab2f4452247a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1c85b2d278b6b6f3ab2ea9dc58" ON "supplier_invoices" ("supplier_id") `);
        await queryRunner.query(`CREATE TABLE "supplier_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "supplier_id" uuid NOT NULL, "payment_date" date NOT NULL, "amount" numeric(14,4) NOT NULL, "payment_method" character varying NOT NULL, "reference" character varying, "created_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_76e86f3194494faf999c652dbf9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_220694212ec38b4aa2fb02ed62" ON "supplier_payments" ("supplier_id") `);
        await queryRunner.query(`CREATE TABLE "supplier_payment_allocations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "supplier_payment_id" uuid NOT NULL, "supplier_invoice_id" uuid NOT NULL, "amount" numeric(14,4) NOT NULL, CONSTRAINT "PK_6b8f3bbd46a51d5f53fa7df22ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_transfers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "from_warehouse_id" uuid NOT NULL, "to_warehouse_id" uuid NOT NULL, "transfer_date" date NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'draft', "notes" text, "created_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ef738a3a4a578c7f1802c1bb50a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_transfer_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "transfer_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity" numeric(14,4) NOT NULL, CONSTRAINT "PK_471b427d94a3f10ca3bcd9de9ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_layers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "warehouse_id" uuid NOT NULL, "quantity_remaining" numeric(14,4) NOT NULL, "unit_cost" numeric(14,4) NOT NULL, "batch_code" character varying(128), "expiry_date" date, "received_at" TIMESTAMP WITH TIME ZONE NOT NULL, "source_ref_type" character varying(32) NOT NULL, "source_ref_id" uuid, "grn_line_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0d7f5e5f0f16936b835b3e58872" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3cdd462343c591906770b28108" ON "stock_layers" ("product_id", "warehouse_id") `);
        await queryRunner.query(`CREATE TABLE "stock_balances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "warehouse_id" uuid NOT NULL, "quantity" numeric(14,4) NOT NULL DEFAULT '0', "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9ec96c724d589b77f6d43546db2" UNIQUE ("product_id", "warehouse_id"), CONSTRAINT "PK_4c0d249ce58f9a559eb7df31b23" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9ec96c724d589b77f6d43546db" ON "stock_balances" ("product_id", "warehouse_id") `);
        await queryRunner.query(`CREATE TABLE "salespersons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "code" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c5718860d306590f6e0f8d8eb34" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "long_name" character varying, "type" character varying NOT NULL, "address" text, "town_id" uuid, "area_id" uuid, "telephone" character varying, "mobile" character varying, "contact_person" character varying, "ntn" character varying, "stn" character varying, "sales_tax_status" character varying NOT NULL DEFAULT 'unregistered', "is_filer" boolean NOT NULL DEFAULT false, "license_no" character varying, "license_expiry_date" date, "contact" jsonb, "credit_limit" numeric(14,4) NOT NULL DEFAULT '0', "payment_terms_id" uuid, "tax_profile_id" uuid, "default_route_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sales_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "order_date" date NOT NULL, "status" character varying NOT NULL DEFAULT 'draft', "warehouse_id" uuid, "salesperson_id" uuid, "subtotal" numeric(14,4) NOT NULL DEFAULT '0', "tax_amount" numeric(14,4) NOT NULL DEFAULT '0', "discount_amount" numeric(14,4) NOT NULL DEFAULT '0', "total" numeric(14,4) NOT NULL DEFAULT '0', "notes" text, "created_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5328297e067ca929fbe7cf989dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sales_order_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sales_order_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity" numeric(14,4) NOT NULL, "unit_price" numeric(14,4) NOT NULL, "tax_amount" numeric(14,4) NOT NULL DEFAULT '0', "discount_amount" numeric(14,4) NOT NULL DEFAULT '0', "delivered_quantity" numeric(14,4) NOT NULL DEFAULT '0', "tax_profile_id" uuid, CONSTRAINT "PK_91a9fd0ffdb8572374cf89df4da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "delivery_routes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "code" character varying NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_114337f048f541ccfe4c5d57140" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "route_stops" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "route_id" uuid NOT NULL, "sequence_order" integer NOT NULL, "customer_id" uuid, "address_line" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_22c09afc24c0a7a13644c629073" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invoice_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_id" uuid NOT NULL, "product_id" uuid NOT NULL, "sales_order_line_id" uuid, "quantity" numeric(14,4) NOT NULL, "unit_price" numeric(14,4) NOT NULL, "tax_amount" numeric(14,4) NOT NULL DEFAULT '0', "discount_amount" numeric(14,4) NOT NULL DEFAULT '0', "tax_profile_id" uuid, CONSTRAINT "PK_3d18eb48142b916f581f0c21a65" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invoice_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(128) NOT NULL, "config" jsonb NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3a8370502b9ce87ef136481ddcf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "invoice_date" date NOT NULL, "due_date" date NOT NULL, "status" character varying NOT NULL DEFAULT 'draft', "payment_type" character varying NOT NULL DEFAULT 'credit', "warehouse_id" uuid NOT NULL, "subtotal" numeric(14,4) NOT NULL DEFAULT '0', "tax_amount" numeric(14,4) NOT NULL DEFAULT '0', "discount_amount" numeric(14,4) NOT NULL DEFAULT '0', "total" numeric(14,4) NOT NULL DEFAULT '0', "notes" text, "sales_order_id" uuid, "salesperson_id" uuid, "created_by" uuid, "invoice_template_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_14d8a44ee1acda919f74b9ef52" ON "invoices" ("invoice_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_da439e6fddbc18cda177c995a7" ON "invoices" ("customer_id", "status") `);
        await queryRunner.query(`CREATE TABLE "receipts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "receipt_date" date NOT NULL, "amount" numeric(14,4) NOT NULL, "payment_method" character varying NOT NULL, "reference" character varying, "created_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5e8182d7c29e023da6e1ff33bfe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7b3c9ac513f95ec0e9efcf6670" ON "receipts" ("customer_id") `);
        await queryRunner.query(`CREATE TABLE "receipt_allocations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "receipt_id" uuid NOT NULL, "invoice_id" uuid NOT NULL, "amount" numeric(14,4) NOT NULL, CONSTRAINT "PK_a651cc7e3a63d31f0ea41d77e83" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_22d465e71d63ad5f9fcb4ca82b" ON "receipt_allocations" ("receipt_id", "invoice_id") `);
        await queryRunner.query(`CREATE TABLE "quotations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "customer_id" uuid NOT NULL, "quotation_date" date NOT NULL, "valid_until" date, "status" character varying NOT NULL DEFAULT 'draft', "subtotal" numeric(14,4) NOT NULL DEFAULT '0', "tax_amount" numeric(14,4) NOT NULL DEFAULT '0', "discount_amount" numeric(14,4) NOT NULL DEFAULT '0', "total" numeric(14,4) NOT NULL DEFAULT '0', "notes" text, "created_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6c00eb8ba181f28c21ffba7ecb1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "quotation_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quotation_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity" numeric(14,4) NOT NULL, "unit_price" numeric(14,4) NOT NULL, "tax_amount" numeric(14,4) NOT NULL DEFAULT '0', "discount_amount" numeric(14,4) NOT NULL DEFAULT '0', "tax_profile_id" uuid, CONSTRAINT "PK_facdcaf4d7c7974c5d9adb63c23" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "delivery_note_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "delivery_note_id" uuid NOT NULL, "product_id" uuid NOT NULL, "quantity" numeric(14,4) NOT NULL, "invoice_line_id" uuid, "sales_order_line_id" uuid, CONSTRAINT "PK_8f0f3dacfb505b215ae221df8dc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "delivery_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "run_date" date NOT NULL, "route_id" uuid NOT NULL, "vehicle_info" character varying, "driver_salesperson_id" uuid, "status" character varying NOT NULL DEFAULT 'draft', "created_by" uuid, "cold_chain_required" boolean NOT NULL DEFAULT false, "controlled_delivery_required" boolean NOT NULL DEFAULT false, "dispatch_compliance_note" text, "delivery_compliance_note" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_744433ad6764ac6d3823ca56452" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "delivery_run_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "delivery_run_id" uuid NOT NULL, "delivery_note_id" uuid NOT NULL, CONSTRAINT "PK_fb9e46b02b361a523b13b60dcc7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "delivery_notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_id" uuid, "sales_order_id" uuid, "delivery_date" date, "status" character varying NOT NULL DEFAULT 'pending', "warehouse_id" uuid, "created_by" uuid, "cold_chain_required" boolean NOT NULL DEFAULT false, "controlled_delivery_required" boolean NOT NULL DEFAULT false, "dispatch_compliance_note" text, "delivery_compliance_note" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8ba22b28b7392ac676c680dd5d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "proof_of_delivery" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "delivery_note_id" uuid NOT NULL, "type" character varying NOT NULL, "reference" text NOT NULL, "notes" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8fc2509dfe6dc0b9eafc522620c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying NOT NULL, "type" character varying(32) NOT NULL, "parent_id" character varying, "is_system" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5a7a02c20412299d198e097a8fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "journal_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entry_date" date NOT NULL, "reference" character varying, "description" text, "status" character varying NOT NULL DEFAULT 'posted', "source_type" character varying, "source_id" uuid, "created_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_a70368e64230434457c8d007ab3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "journal_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "journal_entry_id" uuid NOT NULL, "account_id" uuid NOT NULL, "debit" numeric(14,4) NOT NULL DEFAULT '0', "credit" numeric(14,4) NOT NULL DEFAULT '0', CONSTRAINT "PK_70cba2da4588cee8921f73ef136" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "product_id" uuid NOT NULL, "warehouse_id" uuid NOT NULL, "quantity_delta" numeric(14,4) NOT NULL, "ref_type" character varying NOT NULL, "ref_id" uuid, "unit_cost" numeric(14,4), "movement_date" date NOT NULL, "notes" text, "user_id" uuid, "grn_line_id" uuid, "invoice_line_id" uuid, "stock_transfer_line_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d7597827c1dcffae889db3ab873" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7840357ec6fcad1b337168481a" ON "inventory_movements" ("product_id", "warehouse_id", "movement_date") `);
        await queryRunner.query(`CREATE TABLE "inventory_layer_consumptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "inventory_movement_id" uuid NOT NULL, "stock_layer_id" uuid NOT NULL, "quantity" numeric(14,4) NOT NULL, "unit_cost" numeric(14,4) NOT NULL, CONSTRAINT "PK_ec7e8ab4dbfbfe04e40e881b9a6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "company_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "default_cash_account_id" uuid NOT NULL, "default_bank_account_id" uuid NOT NULL, "company_name" character varying(255) NOT NULL DEFAULT 'Your company', "legal_name" character varying(255), "address_line1" character varying(255), "address_line2" character varying(255), "city" character varying(128), "state" character varying(128), "postal_code" character varying(32), "country" character varying(128), "phone" character varying(64), "email" character varying(255), "tax_registration_number" character varying(128), "logo_url" character varying(2048), "financial_year_start_month" smallint NOT NULL DEFAULT '1', "financial_year_label_override" character varying(64), "currency_code" character varying(3) NOT NULL DEFAULT 'USD', "money_decimals" smallint NOT NULL DEFAULT '2', "quantity_decimals" smallint NOT NULL DEFAULT '2', "rounding_mode" character varying(32) NOT NULL DEFAULT 'half_up', "inventory_costing_method" character varying(8) NOT NULL DEFAULT 'fifo', "period_locked_through" date, "journal_approval_threshold" numeric(14,4), "default_invoice_template_id" uuid, "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_036b4634217db79c17305442dbe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying NOT NULL, "action" character varying NOT NULL, "entity" character varying NOT NULL, "entity_id" character varying, "old_value" jsonb, "new_value" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "approval_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entity_type" character varying(64) NOT NULL, "entity_id" character varying NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'pending', "requested_by" uuid, "reviewed_by" uuid, "review_note" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "reviewed_at" TIMESTAMP, CONSTRAINT "PK_484806bb8ff331b851fc75973c0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("user_id" uuid NOT NULL, "role_id" uuid NOT NULL, CONSTRAINT "PK_23ed6f04fe43066df08379fd034" PRIMARY KEY ("user_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles" ("role_id") `);
        await queryRunner.query(`ALTER TABLE "user_notifications" ADD CONSTRAINT "FK_ae9b1d1f1fe780ef8e3e7d0c0f6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "towns" ADD CONSTRAINT "FK_889969a9649744d69dfb3de2d57" FOREIGN KEY ("area_id") REFERENCES "areas"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_c1e2c406478c2355715918d74aa" FOREIGN KEY ("payment_terms_id") REFERENCES "payment_terms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_80b027cb6dab43b6aa202017ae4" FOREIGN KEY ("tax_profile_id") REFERENCES "tax_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_categories" ADD CONSTRAINT "FK_5f151d414daab0290f65b517ed4" FOREIGN KEY ("parent_id") REFERENCES "product_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_prices" ADD CONSTRAINT "FK_8218c69c7f5a3706662101fa788" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_prices" ADD CONSTRAINT "FK_e3be908efc3cc43dcbcb085fe57" FOREIGN KEY ("price_level_id") REFERENCES "price_levels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_0ec433c1e1d444962d592d86c86" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "product_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_0b97249dd9e17bbc604a5ba3d07" FOREIGN KEY ("unit_id") REFERENCES "units_of_measure"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_lines" ADD CONSTRAINT "FK_c70f4952f88b5bd649151f631c8" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_lines" ADD CONSTRAINT "FK_1b7242d654272b67cfffcd9d6ea" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_lines" ADD CONSTRAINT "FK_5dd62a746e307e79e6d2af90da6" FOREIGN KEY ("tax_profile_id") REFERENCES "tax_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_d16a885aa88447ccfd010e739b0" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_74e4ce03ba3f8bc13de20fc594e" FOREIGN KEY ("warehouse_id") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_99f44faa1ca8d7ec9ebef918b06" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grn_lines" ADD CONSTRAINT "FK_9b86a2a6c242e8b8cead0f93804" FOREIGN KEY ("grn_id") REFERENCES "grns"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grn_lines" ADD CONSTRAINT "FK_02672c2a4cde426aff17ade29ff" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grn_lines" ADD CONSTRAINT "FK_7fd8bec441d3930a441a766d4b1" FOREIGN KEY ("purchase_order_line_id") REFERENCES "purchase_order_lines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grns" ADD CONSTRAINT "FK_b8948b78af50773643eae7bc207" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grns" ADD CONSTRAINT "FK_5bc95a50351873eb540900e522c" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grns" ADD CONSTRAINT "FK_f57637a9179f4df29c9267c3ac9" FOREIGN KEY ("warehouse_id") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "grns" ADD CONSTRAINT "FK_80360ec121d18a0ca75a8e48c7b" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_invoice_lines" ADD CONSTRAINT "FK_30fe58179e89b7a3f80f986c17c" FOREIGN KEY ("supplier_invoice_id") REFERENCES "supplier_invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_invoice_lines" ADD CONSTRAINT "FK_ad01e22ac1c1a4522c699fcb6e9" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_invoice_lines" ADD CONSTRAINT "FK_47277cba987a236c7592cff6680" FOREIGN KEY ("grn_line_id") REFERENCES "grn_lines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_invoice_lines" ADD CONSTRAINT "FK_2031d7d220775d6f8bc5a100557" FOREIGN KEY ("tax_profile_id") REFERENCES "tax_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_invoices" ADD CONSTRAINT "FK_1c85b2d278b6b6f3ab2ea9dc582" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_invoices" ADD CONSTRAINT "FK_ee7df058118fb57ce6e850f2181" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_invoices" ADD CONSTRAINT "FK_4a493d8eacdaef5d11955a5c217" FOREIGN KEY ("grn_id") REFERENCES "grns"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_invoices" ADD CONSTRAINT "FK_83564297cc21bc50c0c17b35205" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_payments" ADD CONSTRAINT "FK_220694212ec38b4aa2fb02ed622" FOREIGN KEY ("supplier_id") REFERENCES "suppliers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_payments" ADD CONSTRAINT "FK_0ef621c98c59626b321265cd34c" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_payment_allocations" ADD CONSTRAINT "FK_a1b286b784673d04848d8ada208" FOREIGN KEY ("supplier_payment_id") REFERENCES "supplier_payments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "supplier_payment_allocations" ADD CONSTRAINT "FK_abf17cc593af9da18575a58a974" FOREIGN KEY ("supplier_invoice_id") REFERENCES "supplier_invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_f30ca9f38766553e46edce7f2a3" FOREIGN KEY ("from_warehouse_id") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_162c14098b490f3993240520fad" FOREIGN KEY ("to_warehouse_id") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" ADD CONSTRAINT "FK_f7b8ce0d2d24cebaeb903d6cf5f" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_lines" ADD CONSTRAINT "FK_f4133789cec434f02b9b2212a81" FOREIGN KEY ("transfer_id") REFERENCES "stock_transfers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_lines" ADD CONSTRAINT "FK_3af34772c6e8deb04deb6a60878" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_layers" ADD CONSTRAINT "FK_5799aeae15c15a156998683df83" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_layers" ADD CONSTRAINT "FK_9b9c02c20da5b787a7caa6a4dda" FOREIGN KEY ("warehouse_id") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_layers" ADD CONSTRAINT "FK_e93399511c849d4b421a7fff9ad" FOREIGN KEY ("grn_line_id") REFERENCES "grn_lines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_balances" ADD CONSTRAINT "FK_b940a160f793ee34c4a057b7c9e" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_balances" ADD CONSTRAINT "FK_ec718dfbbf08afb84b0f665fc0d" FOREIGN KEY ("warehouse_id") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_e50dd9867284a6e91f05e7b72a7" FOREIGN KEY ("town_id") REFERENCES "towns"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_84861ac29ff556eebafaba6ea15" FOREIGN KEY ("area_id") REFERENCES "areas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_3140d53a62dae79763d98ed2125" FOREIGN KEY ("payment_terms_id") REFERENCES "payment_terms"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_ad37daa9d8e821cecea65662cf4" FOREIGN KEY ("tax_profile_id") REFERENCES "tax_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales_orders" ADD CONSTRAINT "FK_1fb56bee917dfd98ada56d626de" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales_orders" ADD CONSTRAINT "FK_d06febc93fc604568a79b11474d" FOREIGN KEY ("warehouse_id") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales_orders" ADD CONSTRAINT "FK_54e4f5cb9ae0ce8b4df92344feb" FOREIGN KEY ("salesperson_id") REFERENCES "salespersons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales_orders" ADD CONSTRAINT "FK_8912b0505ae8f7b20060e50c45b" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales_order_lines" ADD CONSTRAINT "FK_10bb9d379979b7c80578d9b4cda" FOREIGN KEY ("sales_order_id") REFERENCES "sales_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales_order_lines" ADD CONSTRAINT "FK_94351a987335d4452480d5ddf06" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales_order_lines" ADD CONSTRAINT "FK_f174bf6789d8c77c681864b1975" FOREIGN KEY ("tax_profile_id") REFERENCES "tax_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "route_stops" ADD CONSTRAINT "FK_b16cab5c66870949cbb4ee748c0" FOREIGN KEY ("route_id") REFERENCES "delivery_routes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "route_stops" ADD CONSTRAINT "FK_6c8b0c41241761f7b0085982458" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD CONSTRAINT "FK_2da95dc86a54a00ff20ce46d0fe" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD CONSTRAINT "FK_975593df931842435a9c6979c55" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD CONSTRAINT "FK_91ef27d62fd05335614481f5688" FOREIGN KEY ("sales_order_line_id") REFERENCES "sales_order_lines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" ADD CONSTRAINT "FK_dcc499060c1db2646b76288ea6b" FOREIGN KEY ("tax_profile_id") REFERENCES "tax_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_65e3145f317bd655481d3f96c74" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_eccb407d5ddba67ad4ee8fef14f" FOREIGN KEY ("warehouse_id") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_212bea3f86e07d6f487678a989f" FOREIGN KEY ("sales_order_id") REFERENCES "sales_orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_f992d496ecdc51d590e8839bfb2" FOREIGN KEY ("salesperson_id") REFERENCES "salespersons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_39a202af5d1dd1744458820ecb5" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_ad40441877a56c1f29408657784" FOREIGN KEY ("invoice_template_id") REFERENCES "invoice_templates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receipts" ADD CONSTRAINT "FK_7b3c9ac513f95ec0e9efcf6670f" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receipts" ADD CONSTRAINT "FK_eee1cdcc032068c53ba58a7d8e6" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receipt_allocations" ADD CONSTRAINT "FK_3273e0bc08e91c42971722efee7" FOREIGN KEY ("receipt_id") REFERENCES "receipts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "receipt_allocations" ADD CONSTRAINT "FK_8f123895d7c10ad036e2766e11d" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotations" ADD CONSTRAINT "FK_6c655818e6753ed41eb755b8bcb" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotations" ADD CONSTRAINT "FK_25dcb703da984fa66bde99af598" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotation_lines" ADD CONSTRAINT "FK_0b4cc7bc498455d7a87465bb17e" FOREIGN KEY ("quotation_id") REFERENCES "quotations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotation_lines" ADD CONSTRAINT "FK_17059fdcf48d8a764a9ce0efc33" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotation_lines" ADD CONSTRAINT "FK_45a8f91fe9ab311dad4aa73f60a" FOREIGN KEY ("tax_profile_id") REFERENCES "tax_profiles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_note_lines" ADD CONSTRAINT "FK_6069cd7bcdf08e0dca7f15073d1" FOREIGN KEY ("delivery_note_id") REFERENCES "delivery_notes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_note_lines" ADD CONSTRAINT "FK_3030af98bf5cd11b169a55e0975" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_note_lines" ADD CONSTRAINT "FK_500e7092e654703603bc7ee810a" FOREIGN KEY ("invoice_line_id") REFERENCES "invoice_lines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_note_lines" ADD CONSTRAINT "FK_77b54b2c44114ac8427adab845a" FOREIGN KEY ("sales_order_line_id") REFERENCES "sales_order_lines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_runs" ADD CONSTRAINT "FK_48cdb80165eb3e963389b266a80" FOREIGN KEY ("route_id") REFERENCES "delivery_routes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_runs" ADD CONSTRAINT "FK_672fd11041dcc1fb3aa27ec66ae" FOREIGN KEY ("driver_salesperson_id") REFERENCES "salespersons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_runs" ADD CONSTRAINT "FK_5c484a209175895e3768e36b86c" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_run_items" ADD CONSTRAINT "FK_eda536d0ec9a547f56b134e8fba" FOREIGN KEY ("delivery_run_id") REFERENCES "delivery_runs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_run_items" ADD CONSTRAINT "FK_7d198b5aaf66598a903499e3302" FOREIGN KEY ("delivery_note_id") REFERENCES "delivery_notes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_notes" ADD CONSTRAINT "FK_3fea653d7ecb6dced40194d7a20" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_notes" ADD CONSTRAINT "FK_ca4c206507dafaa6bd32e695091" FOREIGN KEY ("sales_order_id") REFERENCES "sales_orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_notes" ADD CONSTRAINT "FK_26c42aa18c4fdb42db640267bf8" FOREIGN KEY ("warehouse_id") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_notes" ADD CONSTRAINT "FK_a506ecec013ae56dc9a4c152b9a" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "proof_of_delivery" ADD CONSTRAINT "FK_901ce05b35e2728f2c1889f9928" FOREIGN KEY ("delivery_note_id") REFERENCES "delivery_notes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journal_entries" ADD CONSTRAINT "FK_dee7f9cf07c67fce5f6018ac32f" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journal_lines" ADD CONSTRAINT "FK_1fd23ae91f0c24764b4e581c72e" FOREIGN KEY ("journal_entry_id") REFERENCES "journal_entries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journal_lines" ADD CONSTRAINT "FK_46bed88ea929e6f0aa17bf20845" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_5c3bec1682252c36fa161587738" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_944a043fd68cb41c7a9f6db160c" FOREIGN KEY ("warehouse_id") REFERENCES "warehouses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_63cca4adcd28b6fe19bc4ceb22f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_fd113b527f47ae3eaa8bff7dc3c" FOREIGN KEY ("grn_line_id") REFERENCES "grn_lines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_1332fa6a8b92e8ec271c78f0875" FOREIGN KEY ("invoice_line_id") REFERENCES "invoice_lines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" ADD CONSTRAINT "FK_0c42b8e1fdc0f74fc9990b11630" FOREIGN KEY ("stock_transfer_line_id") REFERENCES "stock_transfer_lines"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_layer_consumptions" ADD CONSTRAINT "FK_f72bef8f6928553a31592d473fc" FOREIGN KEY ("inventory_movement_id") REFERENCES "inventory_movements"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_layer_consumptions" ADD CONSTRAINT "FK_9deaf52fcf006b31da5a4caa8b0" FOREIGN KEY ("stock_layer_id") REFERENCES "stock_layers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_settings" ADD CONSTRAINT "FK_f7fa085a55af231798f37614d74" FOREIGN KEY ("default_cash_account_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_settings" ADD CONSTRAINT "FK_1a9d2c099b1d79a9eb144b682dc" FOREIGN KEY ("default_bank_account_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "company_settings" ADD CONSTRAINT "FK_3650aa2fd2b47c5133062662c6c" FOREIGN KEY ("default_invoice_template_id") REFERENCES "invoice_templates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_requests" ADD CONSTRAINT "FK_0bcfff2aed6c93f6fa089720b36" FOREIGN KEY ("requested_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "approval_requests" ADD CONSTRAINT "FK_e7f4642ca9d7f6ebfc9fbe2491a" FOREIGN KEY ("reviewed_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "approval_requests" DROP CONSTRAINT "FK_e7f4642ca9d7f6ebfc9fbe2491a"`);
        await queryRunner.query(`ALTER TABLE "approval_requests" DROP CONSTRAINT "FK_0bcfff2aed6c93f6fa089720b36"`);
        await queryRunner.query(`ALTER TABLE "company_settings" DROP CONSTRAINT "FK_3650aa2fd2b47c5133062662c6c"`);
        await queryRunner.query(`ALTER TABLE "company_settings" DROP CONSTRAINT "FK_1a9d2c099b1d79a9eb144b682dc"`);
        await queryRunner.query(`ALTER TABLE "company_settings" DROP CONSTRAINT "FK_f7fa085a55af231798f37614d74"`);
        await queryRunner.query(`ALTER TABLE "inventory_layer_consumptions" DROP CONSTRAINT "FK_9deaf52fcf006b31da5a4caa8b0"`);
        await queryRunner.query(`ALTER TABLE "inventory_layer_consumptions" DROP CONSTRAINT "FK_f72bef8f6928553a31592d473fc"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_0c42b8e1fdc0f74fc9990b11630"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_1332fa6a8b92e8ec271c78f0875"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_fd113b527f47ae3eaa8bff7dc3c"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_63cca4adcd28b6fe19bc4ceb22f"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_944a043fd68cb41c7a9f6db160c"`);
        await queryRunner.query(`ALTER TABLE "inventory_movements" DROP CONSTRAINT "FK_5c3bec1682252c36fa161587738"`);
        await queryRunner.query(`ALTER TABLE "journal_lines" DROP CONSTRAINT "FK_46bed88ea929e6f0aa17bf20845"`);
        await queryRunner.query(`ALTER TABLE "journal_lines" DROP CONSTRAINT "FK_1fd23ae91f0c24764b4e581c72e"`);
        await queryRunner.query(`ALTER TABLE "journal_entries" DROP CONSTRAINT "FK_dee7f9cf07c67fce5f6018ac32f"`);
        await queryRunner.query(`ALTER TABLE "proof_of_delivery" DROP CONSTRAINT "FK_901ce05b35e2728f2c1889f9928"`);
        await queryRunner.query(`ALTER TABLE "delivery_notes" DROP CONSTRAINT "FK_a506ecec013ae56dc9a4c152b9a"`);
        await queryRunner.query(`ALTER TABLE "delivery_notes" DROP CONSTRAINT "FK_26c42aa18c4fdb42db640267bf8"`);
        await queryRunner.query(`ALTER TABLE "delivery_notes" DROP CONSTRAINT "FK_ca4c206507dafaa6bd32e695091"`);
        await queryRunner.query(`ALTER TABLE "delivery_notes" DROP CONSTRAINT "FK_3fea653d7ecb6dced40194d7a20"`);
        await queryRunner.query(`ALTER TABLE "delivery_run_items" DROP CONSTRAINT "FK_7d198b5aaf66598a903499e3302"`);
        await queryRunner.query(`ALTER TABLE "delivery_run_items" DROP CONSTRAINT "FK_eda536d0ec9a547f56b134e8fba"`);
        await queryRunner.query(`ALTER TABLE "delivery_runs" DROP CONSTRAINT "FK_5c484a209175895e3768e36b86c"`);
        await queryRunner.query(`ALTER TABLE "delivery_runs" DROP CONSTRAINT "FK_672fd11041dcc1fb3aa27ec66ae"`);
        await queryRunner.query(`ALTER TABLE "delivery_runs" DROP CONSTRAINT "FK_48cdb80165eb3e963389b266a80"`);
        await queryRunner.query(`ALTER TABLE "delivery_note_lines" DROP CONSTRAINT "FK_77b54b2c44114ac8427adab845a"`);
        await queryRunner.query(`ALTER TABLE "delivery_note_lines" DROP CONSTRAINT "FK_500e7092e654703603bc7ee810a"`);
        await queryRunner.query(`ALTER TABLE "delivery_note_lines" DROP CONSTRAINT "FK_3030af98bf5cd11b169a55e0975"`);
        await queryRunner.query(`ALTER TABLE "delivery_note_lines" DROP CONSTRAINT "FK_6069cd7bcdf08e0dca7f15073d1"`);
        await queryRunner.query(`ALTER TABLE "quotation_lines" DROP CONSTRAINT "FK_45a8f91fe9ab311dad4aa73f60a"`);
        await queryRunner.query(`ALTER TABLE "quotation_lines" DROP CONSTRAINT "FK_17059fdcf48d8a764a9ce0efc33"`);
        await queryRunner.query(`ALTER TABLE "quotation_lines" DROP CONSTRAINT "FK_0b4cc7bc498455d7a87465bb17e"`);
        await queryRunner.query(`ALTER TABLE "quotations" DROP CONSTRAINT "FK_25dcb703da984fa66bde99af598"`);
        await queryRunner.query(`ALTER TABLE "quotations" DROP CONSTRAINT "FK_6c655818e6753ed41eb755b8bcb"`);
        await queryRunner.query(`ALTER TABLE "receipt_allocations" DROP CONSTRAINT "FK_8f123895d7c10ad036e2766e11d"`);
        await queryRunner.query(`ALTER TABLE "receipt_allocations" DROP CONSTRAINT "FK_3273e0bc08e91c42971722efee7"`);
        await queryRunner.query(`ALTER TABLE "receipts" DROP CONSTRAINT "FK_eee1cdcc032068c53ba58a7d8e6"`);
        await queryRunner.query(`ALTER TABLE "receipts" DROP CONSTRAINT "FK_7b3c9ac513f95ec0e9efcf6670f"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_ad40441877a56c1f29408657784"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_39a202af5d1dd1744458820ecb5"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_f992d496ecdc51d590e8839bfb2"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_212bea3f86e07d6f487678a989f"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_eccb407d5ddba67ad4ee8fef14f"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_65e3145f317bd655481d3f96c74"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP CONSTRAINT "FK_dcc499060c1db2646b76288ea6b"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP CONSTRAINT "FK_91ef27d62fd05335614481f5688"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP CONSTRAINT "FK_975593df931842435a9c6979c55"`);
        await queryRunner.query(`ALTER TABLE "invoice_lines" DROP CONSTRAINT "FK_2da95dc86a54a00ff20ce46d0fe"`);
        await queryRunner.query(`ALTER TABLE "route_stops" DROP CONSTRAINT "FK_6c8b0c41241761f7b0085982458"`);
        await queryRunner.query(`ALTER TABLE "route_stops" DROP CONSTRAINT "FK_b16cab5c66870949cbb4ee748c0"`);
        await queryRunner.query(`ALTER TABLE "sales_order_lines" DROP CONSTRAINT "FK_f174bf6789d8c77c681864b1975"`);
        await queryRunner.query(`ALTER TABLE "sales_order_lines" DROP CONSTRAINT "FK_94351a987335d4452480d5ddf06"`);
        await queryRunner.query(`ALTER TABLE "sales_order_lines" DROP CONSTRAINT "FK_10bb9d379979b7c80578d9b4cda"`);
        await queryRunner.query(`ALTER TABLE "sales_orders" DROP CONSTRAINT "FK_8912b0505ae8f7b20060e50c45b"`);
        await queryRunner.query(`ALTER TABLE "sales_orders" DROP CONSTRAINT "FK_54e4f5cb9ae0ce8b4df92344feb"`);
        await queryRunner.query(`ALTER TABLE "sales_orders" DROP CONSTRAINT "FK_d06febc93fc604568a79b11474d"`);
        await queryRunner.query(`ALTER TABLE "sales_orders" DROP CONSTRAINT "FK_1fb56bee917dfd98ada56d626de"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_ad37daa9d8e821cecea65662cf4"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_3140d53a62dae79763d98ed2125"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_84861ac29ff556eebafaba6ea15"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_e50dd9867284a6e91f05e7b72a7"`);
        await queryRunner.query(`ALTER TABLE "stock_balances" DROP CONSTRAINT "FK_ec718dfbbf08afb84b0f665fc0d"`);
        await queryRunner.query(`ALTER TABLE "stock_balances" DROP CONSTRAINT "FK_b940a160f793ee34c4a057b7c9e"`);
        await queryRunner.query(`ALTER TABLE "stock_layers" DROP CONSTRAINT "FK_e93399511c849d4b421a7fff9ad"`);
        await queryRunner.query(`ALTER TABLE "stock_layers" DROP CONSTRAINT "FK_9b9c02c20da5b787a7caa6a4dda"`);
        await queryRunner.query(`ALTER TABLE "stock_layers" DROP CONSTRAINT "FK_5799aeae15c15a156998683df83"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_lines" DROP CONSTRAINT "FK_3af34772c6e8deb04deb6a60878"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_lines" DROP CONSTRAINT "FK_f4133789cec434f02b9b2212a81"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_f7b8ce0d2d24cebaeb903d6cf5f"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_162c14098b490f3993240520fad"`);
        await queryRunner.query(`ALTER TABLE "stock_transfers" DROP CONSTRAINT "FK_f30ca9f38766553e46edce7f2a3"`);
        await queryRunner.query(`ALTER TABLE "supplier_payment_allocations" DROP CONSTRAINT "FK_abf17cc593af9da18575a58a974"`);
        await queryRunner.query(`ALTER TABLE "supplier_payment_allocations" DROP CONSTRAINT "FK_a1b286b784673d04848d8ada208"`);
        await queryRunner.query(`ALTER TABLE "supplier_payments" DROP CONSTRAINT "FK_0ef621c98c59626b321265cd34c"`);
        await queryRunner.query(`ALTER TABLE "supplier_payments" DROP CONSTRAINT "FK_220694212ec38b4aa2fb02ed622"`);
        await queryRunner.query(`ALTER TABLE "supplier_invoices" DROP CONSTRAINT "FK_83564297cc21bc50c0c17b35205"`);
        await queryRunner.query(`ALTER TABLE "supplier_invoices" DROP CONSTRAINT "FK_4a493d8eacdaef5d11955a5c217"`);
        await queryRunner.query(`ALTER TABLE "supplier_invoices" DROP CONSTRAINT "FK_ee7df058118fb57ce6e850f2181"`);
        await queryRunner.query(`ALTER TABLE "supplier_invoices" DROP CONSTRAINT "FK_1c85b2d278b6b6f3ab2ea9dc582"`);
        await queryRunner.query(`ALTER TABLE "supplier_invoice_lines" DROP CONSTRAINT "FK_2031d7d220775d6f8bc5a100557"`);
        await queryRunner.query(`ALTER TABLE "supplier_invoice_lines" DROP CONSTRAINT "FK_47277cba987a236c7592cff6680"`);
        await queryRunner.query(`ALTER TABLE "supplier_invoice_lines" DROP CONSTRAINT "FK_ad01e22ac1c1a4522c699fcb6e9"`);
        await queryRunner.query(`ALTER TABLE "supplier_invoice_lines" DROP CONSTRAINT "FK_30fe58179e89b7a3f80f986c17c"`);
        await queryRunner.query(`ALTER TABLE "grns" DROP CONSTRAINT "FK_80360ec121d18a0ca75a8e48c7b"`);
        await queryRunner.query(`ALTER TABLE "grns" DROP CONSTRAINT "FK_f57637a9179f4df29c9267c3ac9"`);
        await queryRunner.query(`ALTER TABLE "grns" DROP CONSTRAINT "FK_5bc95a50351873eb540900e522c"`);
        await queryRunner.query(`ALTER TABLE "grns" DROP CONSTRAINT "FK_b8948b78af50773643eae7bc207"`);
        await queryRunner.query(`ALTER TABLE "grn_lines" DROP CONSTRAINT "FK_7fd8bec441d3930a441a766d4b1"`);
        await queryRunner.query(`ALTER TABLE "grn_lines" DROP CONSTRAINT "FK_02672c2a4cde426aff17ade29ff"`);
        await queryRunner.query(`ALTER TABLE "grn_lines" DROP CONSTRAINT "FK_9b86a2a6c242e8b8cead0f93804"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_99f44faa1ca8d7ec9ebef918b06"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_74e4ce03ba3f8bc13de20fc594e"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_d16a885aa88447ccfd010e739b0"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_lines" DROP CONSTRAINT "FK_5dd62a746e307e79e6d2af90da6"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_lines" DROP CONSTRAINT "FK_1b7242d654272b67cfffcd9d6ea"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_lines" DROP CONSTRAINT "FK_c70f4952f88b5bd649151f631c8"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_0b97249dd9e17bbc604a5ba3d07"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_0ec433c1e1d444962d592d86c86"`);
        await queryRunner.query(`ALTER TABLE "product_prices" DROP CONSTRAINT "FK_e3be908efc3cc43dcbcb085fe57"`);
        await queryRunner.query(`ALTER TABLE "product_prices" DROP CONSTRAINT "FK_8218c69c7f5a3706662101fa788"`);
        await queryRunner.query(`ALTER TABLE "product_categories" DROP CONSTRAINT "FK_5f151d414daab0290f65b517ed4"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_80b027cb6dab43b6aa202017ae4"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_c1e2c406478c2355715918d74aa"`);
        await queryRunner.query(`ALTER TABLE "towns" DROP CONSTRAINT "FK_889969a9649744d69dfb3de2d57"`);
        await queryRunner.query(`ALTER TABLE "user_notifications" DROP CONSTRAINT "FK_ae9b1d1f1fe780ef8e3e7d0c0f6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "approval_requests"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "company_settings"`);
        await queryRunner.query(`DROP TABLE "inventory_layer_consumptions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7840357ec6fcad1b337168481a"`);
        await queryRunner.query(`DROP TABLE "inventory_movements"`);
        await queryRunner.query(`DROP TABLE "journal_lines"`);
        await queryRunner.query(`DROP TABLE "journal_entries"`);
        await queryRunner.query(`DROP TABLE "accounts"`);
        await queryRunner.query(`DROP TABLE "proof_of_delivery"`);
        await queryRunner.query(`DROP TABLE "delivery_notes"`);
        await queryRunner.query(`DROP TABLE "delivery_run_items"`);
        await queryRunner.query(`DROP TABLE "delivery_runs"`);
        await queryRunner.query(`DROP TABLE "delivery_note_lines"`);
        await queryRunner.query(`DROP TABLE "quotation_lines"`);
        await queryRunner.query(`DROP TABLE "quotations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22d465e71d63ad5f9fcb4ca82b"`);
        await queryRunner.query(`DROP TABLE "receipt_allocations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b3c9ac513f95ec0e9efcf6670"`);
        await queryRunner.query(`DROP TABLE "receipts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da439e6fddbc18cda177c995a7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14d8a44ee1acda919f74b9ef52"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TABLE "invoice_templates"`);
        await queryRunner.query(`DROP TABLE "invoice_lines"`);
        await queryRunner.query(`DROP TABLE "route_stops"`);
        await queryRunner.query(`DROP TABLE "delivery_routes"`);
        await queryRunner.query(`DROP TABLE "sales_order_lines"`);
        await queryRunner.query(`DROP TABLE "sales_orders"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TABLE "salespersons"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ec96c724d589b77f6d43546db"`);
        await queryRunner.query(`DROP TABLE "stock_balances"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3cdd462343c591906770b28108"`);
        await queryRunner.query(`DROP TABLE "stock_layers"`);
        await queryRunner.query(`DROP TABLE "stock_transfer_lines"`);
        await queryRunner.query(`DROP TABLE "stock_transfers"`);
        await queryRunner.query(`DROP TABLE "supplier_payment_allocations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_220694212ec38b4aa2fb02ed62"`);
        await queryRunner.query(`DROP TABLE "supplier_payments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1c85b2d278b6b6f3ab2ea9dc58"`);
        await queryRunner.query(`DROP TABLE "supplier_invoices"`);
        await queryRunner.query(`DROP TABLE "supplier_invoice_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8948b78af50773643eae7bc20"`);
        await queryRunner.query(`DROP TABLE "grns"`);
        await queryRunner.query(`DROP TABLE "grn_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d16a885aa88447ccfd010e739b"`);
        await queryRunner.query(`DROP TABLE "purchase_orders"`);
        await queryRunner.query(`DROP TABLE "purchase_order_lines"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "product_prices"`);
        await queryRunner.query(`DROP TABLE "price_levels"`);
        await queryRunner.query(`DROP TABLE "product_categories"`);
        await queryRunner.query(`DROP TABLE "suppliers"`);
        await queryRunner.query(`DROP TABLE "payment_terms"`);
        await queryRunner.query(`DROP TABLE "tax_profiles"`);
        await queryRunner.query(`DROP TABLE "towns"`);
        await queryRunner.query(`DROP TABLE "areas"`);
        await queryRunner.query(`DROP TABLE "units_of_measure"`);
        await queryRunner.query(`DROP TABLE "user_notifications"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "warehouses"`);
    }

}
