/** Thin controller layer — report SQL lives in services/reports/. */
export {
  dailySales,
  stockMovement,
  fastMoving,
  expenseAnalysis,
  receivablesAging,
  payablesAging,
  trialBalance,
  profitLoss,
  balanceSheet,
  taxCollected,
  taxPaid,
  taxSummary,
  deadStock,
  slowMoving,
  grnInvoiceReconciliation,
  dashboardKpis,
  purchaseVsSales,
  profitByProduct,
  profitByCustomer,
  cashFlow,
} from '../services/reports';
