import { z } from 'zod';
import { loginSchema, patchAuthMeSchema, loginResponseSchema } from '@tradeflow/shared';
import {
  createAccountSchema,
  updateAccountSchema,
  createJournalEntrySchema,
  updateJournalEntrySchema,
  updateCompanyAccountingSettingsSchema,
} from '@tradeflow/shared';
import {
  createProductCategorySchema,
  updateProductCategorySchema,
  createUnitSchema,
  updateUnitSchema,
  createPriceLevelSchema,
  updatePriceLevelSchema,
  createProductSchema,
  updateProductSchema,
  replaceProductPricesSchema,
  createCustomerSchema,
  updateCustomerSchema,
  createCustomerTypeSchema,
  updateCustomerTypeSchema,
  createTownSchema,
  updateTownSchema,
  createAreaSchema,
  updateAreaSchema,
  createSupplierSchema,
  updateSupplierSchema,
  createWarehouseSchema,
  updateWarehouseSchema,
  createSalespersonSchema,
  updateSalespersonSchema,
  createTaxProfileSchema,
  updateTaxProfileSchema,
  createPaymentTermsSchema,
  updatePaymentTermsSchema,
  createBonusRuleSchema,
  updateBonusRuleSchema,
} from '@tradeflow/shared';
import {
  postOpeningBalanceSchema,
  postStockAdjustmentSchema,
  createStockTransferSchema,
} from '@tradeflow/shared';
import {
  createQuotationSchema,
  updateQuotationSchema,
  createSalesOrderSchema,
  updateSalesOrderSchema,
  bulkSalesOrdersSchema,
  convertOrderToInvoiceSchema,
  createInvoiceSchema,
  updateInvoiceSchema,
  printInvoicesBatchSchema,
  createReceiptSchema,
} from '@tradeflow/shared';
import {
  createPurchaseOrderSchema,
  updatePurchaseOrderSchema,
  createGrnSchema,
  updateGrnSchema,
  createSupplierInvoiceSchema,
  updateSupplierInvoiceSchema,
  createSupplierPaymentSchema,
  createPurchaseReturnSchema,
  updatePurchaseReturnSchema,
} from '@tradeflow/shared';
import {
  patchGeneralSettingsSchema,
  patchCompanyProfileSchema,
  createInvoiceTemplateSchema,
  updateInvoiceTemplateSchema,
} from '@tradeflow/shared';
import {
  buildPathsFromSpecs,
  crudSpecs,
  dateRangeQuery,
  asOfQuery,
  idPathParams,
  paginationQuery,
  reportRouteSpec,
  type RouteSpec,
} from './helpers';
import { authMeResponseSchema, healthResponseSchema } from '@tradeflow/shared';

const reviewBodySchema = z.object({
  note: z.string().max(2000).optional(),
});

/** All OpenAPI path operations — keep in sync with apps/api/src/routes */
export function buildApiPaths() {
  const specs: RouteSpec[] = [
    {
      method: 'get',
      path: '/health',
      summary: 'Health check',
      tag: 'Health',
      secured: false,
      responseSchema: healthResponseSchema,
    },

    {
      method: 'post',
      path: '/auth/login',
      summary: 'Login',
      tag: 'Auth',
      secured: false,
      body: loginSchema,
      successStatus: 200,
      responseSchema: loginResponseSchema,
    },
    {
      method: 'get',
      path: '/auth/me',
      summary: 'Current user',
      tag: 'Auth',
      responseSchema: authMeResponseSchema,
    },
    {
      method: 'patch',
      path: '/auth/me',
      summary: 'Update current user',
      tag: 'Auth',
      body: patchAuthMeSchema,
      responseSchema: authMeResponseSchema,
    },

    { method: 'get', path: '/audit-logs', summary: 'List audit logs', tag: 'Audit', query: paginationQuery },
    {
      method: 'get',
      path: '/recycle-bin',
      summary: 'List soft-deleted items',
      tag: 'Audit',
      query: paginationQuery,
    },
    {
      method: 'post',
      path: '/recycle-bin/{entity}/{id}/restore',
      summary: 'Restore soft-deleted entity',
      tag: 'Audit',
      pathParams: z.object({ entity: z.string(), id: z.string().uuid() }),
    },

    ...crudSpecs('/product-categories', 'Masters', {
      resourceName: 'product categories',
      createSchema: createProductCategorySchema,
      updateSchema: updateProductCategorySchema,
    }),
    ...crudSpecs('/units', 'Masters', {
      resourceName: 'units',
      createSchema: createUnitSchema,
      updateSchema: updateUnitSchema,
    }),
    ...crudSpecs('/price-levels', 'Masters', {
      resourceName: 'price levels',
      createSchema: createPriceLevelSchema,
      updateSchema: updatePriceLevelSchema,
    }).filter((s) => s.method !== 'delete'),
    ...crudSpecs('/customers', 'Masters', {
      resourceName: 'customers',
      createSchema: createCustomerSchema,
      updateSchema: updateCustomerSchema,
    }),
    {
      method: 'get',
      path: '/customers/{id}/statement',
      summary: 'Customer statement',
      tag: 'Masters',
      pathParams: idPathParams,
      query: dateRangeQuery,
    },
    ...crudSpecs('/customer-types', 'Masters', {
      resourceName: 'customer types',
      createSchema: createCustomerTypeSchema,
      updateSchema: updateCustomerTypeSchema,
    }),
    ...crudSpecs('/towns', 'Masters', {
      resourceName: 'towns',
      createSchema: createTownSchema,
      updateSchema: updateTownSchema,
    }),
    ...crudSpecs('/areas', 'Masters', {
      resourceName: 'areas',
      createSchema: createAreaSchema,
      updateSchema: updateAreaSchema,
    }),
    ...crudSpecs('/suppliers', 'Masters', {
      resourceName: 'suppliers',
      createSchema: createSupplierSchema,
      updateSchema: updateSupplierSchema,
    }),
    {
      method: 'get',
      path: '/suppliers/{id}/statement',
      summary: 'Supplier statement',
      tag: 'Masters',
      pathParams: idPathParams,
      query: dateRangeQuery,
    },
    {
      method: 'get',
      path: '/suppliers/{id}/pricing-history',
      summary: 'Supplier pricing history',
      tag: 'Masters',
      pathParams: idPathParams,
      query: paginationQuery,
    },
    ...crudSpecs('/warehouses', 'Masters', {
      resourceName: 'warehouses',
      createSchema: createWarehouseSchema,
      updateSchema: updateWarehouseSchema,
    }).filter((s) => s.method !== 'delete'),
    ...crudSpecs('/salespersons', 'Masters', {
      resourceName: 'salespersons',
      createSchema: createSalespersonSchema,
      updateSchema: updateSalespersonSchema,
    }),
    ...crudSpecs('/tax-profiles', 'Masters', {
      resourceName: 'tax profiles',
      createSchema: createTaxProfileSchema,
      updateSchema: updateTaxProfileSchema,
    }),
    ...crudSpecs('/payment-terms', 'Masters', {
      resourceName: 'payment terms',
      createSchema: createPaymentTermsSchema,
      updateSchema: updatePaymentTermsSchema,
    }),
    ...crudSpecs('/bonus-rules', 'Masters', {
      resourceName: 'bonus rules',
      createSchema: createBonusRuleSchema,
      updateSchema: updateBonusRuleSchema,
    }),
    {
      method: 'get',
      path: '/bonus-rules/calculate',
      summary: 'Calculate bonus quantity',
      tag: 'Masters',
      query: z.object({
        productId: z.string().uuid(),
        quantity: z.coerce.number().optional(),
      }),
    },

    {
      method: 'get',
      path: '/products',
      summary: 'List products',
      tag: 'Masters',
      query: paginationQuery,
      itemSchema: createProductSchema,
    },
    {
      method: 'post',
      path: '/products',
      summary: 'Create product',
      tag: 'Masters',
      body: createProductSchema,
      successStatus: 201,
      itemSchema: createProductSchema,
    },
    {
      method: 'get',
      path: '/products/lookup/barcode/{barcode}',
      summary: 'Lookup product by barcode',
      tag: 'Masters',
      pathParams: z.object({ barcode: z.string() }),
      itemSchema: createProductSchema,
    },
    {
      method: 'get',
      path: '/products/{id}',
      summary: 'Get product',
      tag: 'Masters',
      pathParams: idPathParams,
      itemSchema: createProductSchema,
    },
    {
      method: 'patch',
      path: '/products/{id}',
      summary: 'Update product',
      tag: 'Masters',
      pathParams: idPathParams,
      body: updateProductSchema,
      itemSchema: createProductSchema,
    },
    {
      method: 'delete',
      path: '/products/{id}',
      summary: 'Delete product',
      tag: 'Masters',
      pathParams: idPathParams,
    },
    {
      method: 'get',
      path: '/products/{id}/prices',
      summary: 'Get product prices',
      tag: 'Masters',
      pathParams: idPathParams,
    },
    {
      method: 'put',
      path: '/products/{id}/prices',
      summary: 'Replace product prices',
      tag: 'Masters',
      pathParams: idPathParams,
      body: replaceProductPricesSchema,
    },

    ...crudSpecs('/quotations', 'Sales', {
      resourceName: 'quotations',
      createSchema: createQuotationSchema,
      updateSchema: updateQuotationSchema,
    }),
    {
      method: 'post',
      path: '/quotations/{id}/convert-to-order',
      summary: 'Convert quotation to sales order',
      tag: 'Sales',
      pathParams: idPathParams,
    },

    {
      method: 'get',
      path: '/sales-orders',
      summary: 'List sales orders',
      tag: 'Sales',
      query: paginationQuery,
      itemSchema: createSalesOrderSchema,
    },
    {
      method: 'post',
      path: '/sales-orders',
      summary: 'Create sales order',
      tag: 'Sales',
      body: createSalesOrderSchema,
      successStatus: 201,
      itemSchema: createSalesOrderSchema,
    },
    {
      method: 'get',
      path: '/sales-orders/{id}',
      summary: 'Get sales order',
      tag: 'Sales',
      pathParams: idPathParams,
      itemSchema: createSalesOrderSchema,
    },
    {
      method: 'patch',
      path: '/sales-orders/{id}',
      summary: 'Update sales order',
      tag: 'Sales',
      pathParams: idPathParams,
      body: updateSalesOrderSchema,
      itemSchema: createSalesOrderSchema,
    },
    {
      method: 'post',
      path: '/sales-orders/bulk',
      summary: 'Bulk confirm/delete sales orders',
      tag: 'Sales',
      body: bulkSalesOrdersSchema,
    },
    {
      method: 'post',
      path: '/sales-orders/{id}/confirm',
      summary: 'Confirm sales order',
      tag: 'Sales',
      pathParams: idPathParams,
    },
    {
      method: 'delete',
      path: '/sales-orders/{id}',
      summary: 'Delete sales order',
      tag: 'Sales',
      pathParams: idPathParams,
    },
    {
      method: 'post',
      path: '/sales-orders/{id}/convert-to-invoice',
      summary: 'Convert sales order to invoice',
      tag: 'Sales',
      pathParams: idPathParams,
      body: convertOrderToInvoiceSchema,
    },

    {
      method: 'get',
      path: '/invoices',
      summary: 'List invoices',
      tag: 'Sales',
      query: paginationQuery,
      itemSchema: createInvoiceSchema,
    },
    {
      method: 'post',
      path: '/invoices',
      summary: 'Create invoice',
      tag: 'Sales',
      body: createInvoiceSchema,
      successStatus: 201,
      itemSchema: createInvoiceSchema,
    },
    {
      method: 'post',
      path: '/invoices/print-batch',
      summary: 'Batch print invoices',
      tag: 'Sales',
      body: printInvoicesBatchSchema,
    },
    {
      method: 'get',
      path: '/invoices/{id}',
      summary: 'Get invoice',
      tag: 'Sales',
      pathParams: idPathParams,
      itemSchema: createInvoiceSchema,
    },
    {
      method: 'patch',
      path: '/invoices/{id}',
      summary: 'Update invoice',
      tag: 'Sales',
      pathParams: idPathParams,
      body: updateInvoiceSchema,
      itemSchema: createInvoiceSchema,
    },
    {
      method: 'delete',
      path: '/invoices/{id}',
      summary: 'Delete invoice',
      tag: 'Sales',
      pathParams: idPathParams,
    },
    {
      method: 'post',
      path: '/invoices/{id}/post',
      summary: 'Post invoice',
      tag: 'Sales',
      pathParams: idPathParams,
    },
    {
      method: 'get',
      path: '/invoices/{id}/print',
      summary: 'Invoice print HTML',
      tag: 'Sales',
      pathParams: idPathParams,
    },

    {
      method: 'get',
      path: '/receipts',
      summary: 'List receipts',
      tag: 'Sales',
      query: paginationQuery,
      itemSchema: createReceiptSchema,
    },
    {
      method: 'get',
      path: '/receipts/{id}',
      summary: 'Get receipt',
      tag: 'Sales',
      pathParams: idPathParams,
      itemSchema: createReceiptSchema,
    },
    {
      method: 'post',
      path: '/receipts',
      summary: 'Create receipt',
      tag: 'Sales',
      body: createReceiptSchema,
      successStatus: 201,
      itemSchema: createReceiptSchema,
    },

    ...crudSpecs('/purchase-orders', 'Purchases', {
      resourceName: 'purchase orders',
      createSchema: createPurchaseOrderSchema,
      updateSchema: updatePurchaseOrderSchema,
    }),
    {
      method: 'post',
      path: '/purchase-orders/{id}/send',
      summary: 'Send purchase order',
      tag: 'Purchases',
      pathParams: idPathParams,
    },
    {
      method: 'get',
      path: '/purchase-orders/{id}/grn-eligible',
      summary: 'GRN-eligible PO lines',
      tag: 'Purchases',
      pathParams: idPathParams,
    },

    {
      method: 'get',
      path: '/grns',
      summary: 'List GRNs',
      tag: 'Purchases',
      query: paginationQuery,
      itemSchema: createGrnSchema,
    },
    {
      method: 'get',
      path: '/grns/pending-invoice-count',
      summary: 'Pending GRN invoice count',
      tag: 'Purchases',
    },
    {
      method: 'post',
      path: '/grns',
      summary: 'Create GRN',
      tag: 'Purchases',
      body: createGrnSchema,
      successStatus: 201,
      itemSchema: createGrnSchema,
    },
    {
      method: 'get',
      path: '/grns/{id}',
      summary: 'Get GRN',
      tag: 'Purchases',
      pathParams: idPathParams,
      itemSchema: createGrnSchema,
    },
    {
      method: 'patch',
      path: '/grns/{id}',
      summary: 'Update GRN',
      tag: 'Purchases',
      pathParams: idPathParams,
      body: updateGrnSchema,
      itemSchema: createGrnSchema,
    },
    {
      method: 'post',
      path: '/grns/{id}/post',
      summary: 'Post GRN',
      tag: 'Purchases',
      pathParams: idPathParams,
    },
    {
      method: 'post',
      path: '/grns/{id}/create-supplier-invoice-draft',
      summary: 'Create supplier invoice draft from GRN',
      tag: 'Purchases',
      pathParams: idPathParams,
      successStatus: 201,
    },

    ...crudSpecs('/supplier-invoices', 'Purchases', {
      resourceName: 'supplier invoices',
      createSchema: createSupplierInvoiceSchema,
      updateSchema: updateSupplierInvoiceSchema,
    }),
    {
      method: 'get',
      path: '/supplier-invoices/open',
      summary: 'Open supplier invoices',
      tag: 'Purchases',
      query: paginationQuery,
      itemSchema: createSupplierInvoiceSchema,
    },
    {
      method: 'post',
      path: '/supplier-invoices/{id}/post',
      summary: 'Post supplier invoice',
      tag: 'Purchases',
      pathParams: idPathParams,
    },
    {
      method: 'delete',
      path: '/supplier-invoices/{id}',
      summary: 'Delete supplier invoice',
      tag: 'Purchases',
      pathParams: idPathParams,
    },

    {
      method: 'get',
      path: '/supplier-payments',
      summary: 'List supplier payments',
      tag: 'Purchases',
      query: paginationQuery,
      itemSchema: createSupplierPaymentSchema,
    },
    {
      method: 'get',
      path: '/supplier-payments/{id}',
      summary: 'Get supplier payment',
      tag: 'Purchases',
      pathParams: idPathParams,
      itemSchema: createSupplierPaymentSchema,
    },
    {
      method: 'post',
      path: '/supplier-payments',
      summary: 'Create supplier payment',
      tag: 'Purchases',
      body: createSupplierPaymentSchema,
      successStatus: 201,
      itemSchema: createSupplierPaymentSchema,
    },

    ...crudSpecs('/purchase-returns', 'Purchases', {
      resourceName: 'purchase returns',
      createSchema: createPurchaseReturnSchema,
      updateSchema: updatePurchaseReturnSchema,
    }),
    {
      method: 'post',
      path: '/purchase-returns/{id}/post',
      summary: 'Post purchase return',
      tag: 'Purchases',
      pathParams: idPathParams,
    },

    {
      method: 'get',
      path: '/inventory/balances',
      summary: 'Stock balances',
      tag: 'Inventory',
      query: paginationQuery,
    },
    {
      method: 'get',
      path: '/inventory/balances/batches',
      summary: 'Stock balances by batch',
      tag: 'Inventory',
      query: paginationQuery,
    },
    {
      method: 'get',
      path: '/inventory/balances/low-stock',
      summary: 'Low stock report',
      tag: 'Inventory',
      query: paginationQuery,
    },
    {
      method: 'get',
      path: '/inventory/movements',
      summary: 'Inventory movements',
      tag: 'Inventory',
      query: paginationQuery,
    },
    {
      method: 'post',
      path: '/inventory/opening-balance',
      summary: 'Opening balance',
      tag: 'Inventory',
      body: postOpeningBalanceSchema,
    },
    {
      method: 'post',
      path: '/inventory/adjustment',
      summary: 'Inventory adjustment',
      tag: 'Inventory',
      body: postStockAdjustmentSchema,
    },

    {
      method: 'get',
      path: '/stock-transfers',
      summary: 'List stock transfers',
      tag: 'Inventory',
      query: paginationQuery,
      itemSchema: createStockTransferSchema,
    },
    {
      method: 'get',
      path: '/stock-transfers/{id}',
      summary: 'Get stock transfer',
      tag: 'Inventory',
      pathParams: idPathParams,
      itemSchema: createStockTransferSchema,
    },
    {
      method: 'post',
      path: '/stock-transfers',
      summary: 'Create stock transfer',
      tag: 'Inventory',
      body: createStockTransferSchema,
      successStatus: 201,
      itemSchema: createStockTransferSchema,
    },
    {
      method: 'post',
      path: '/stock-transfers/{id}/post',
      summary: 'Post stock transfer',
      tag: 'Inventory',
      pathParams: idPathParams,
    },

    ...crudSpecs('/accounts', 'Accounting', {
      resourceName: 'GL accounts',
      createSchema: createAccountSchema,
      updateSchema: updateAccountSchema,
    }).filter((s) => s.method !== 'delete'),
    {
      method: 'get',
      path: '/accounts/{id}/balance',
      summary: 'Account balance',
      tag: 'Accounting',
      pathParams: idPathParams,
      query: dateRangeQuery,
    },

    {
      method: 'get',
      path: '/journal-entries',
      summary: 'List journal entries',
      tag: 'Accounting',
      query: paginationQuery,
      itemSchema: createJournalEntrySchema,
    },
    {
      method: 'get',
      path: '/journal-entries/{id}',
      summary: 'Get journal entry',
      tag: 'Accounting',
      pathParams: idPathParams,
      itemSchema: createJournalEntrySchema,
    },
    {
      method: 'post',
      path: '/journal-entries',
      summary: 'Create journal entry',
      tag: 'Accounting',
      body: createJournalEntrySchema,
      successStatus: 201,
      itemSchema: createJournalEntrySchema,
    },
    {
      method: 'patch',
      path: '/journal-entries/{id}',
      summary: 'Update journal entry',
      tag: 'Accounting',
      pathParams: idPathParams,
      body: updateJournalEntrySchema,
      itemSchema: createJournalEntrySchema,
    },
    {
      method: 'delete',
      path: '/journal-entries/{id}',
      summary: 'Delete journal entry',
      tag: 'Accounting',
      pathParams: idPathParams,
    },
    {
      method: 'post',
      path: '/journal-entries/{id}/post',
      summary: 'Post journal entry',
      tag: 'Accounting',
      pathParams: idPathParams,
    },
    {
      method: 'post',
      path: '/journal-entries/{id}/reverse',
      summary: 'Reverse journal entry',
      tag: 'Accounting',
      pathParams: idPathParams,
    },

    { method: 'get', path: '/settings/general', summary: 'Get general settings', tag: 'Settings' },
    {
      method: 'patch',
      path: '/settings/general',
      summary: 'Update general settings',
      tag: 'Settings',
      body: patchGeneralSettingsSchema,
    },
    { method: 'get', path: '/settings/company', summary: 'Get company profile', tag: 'Settings' },
    {
      method: 'patch',
      path: '/settings/company',
      summary: 'Update company profile',
      tag: 'Settings',
      body: patchCompanyProfileSchema,
    },
    { method: 'get', path: '/settings/accounting', summary: 'Get accounting settings', tag: 'Settings' },
    {
      method: 'patch',
      path: '/settings/accounting',
      summary: 'Update accounting settings',
      tag: 'Settings',
      body: updateCompanyAccountingSettingsSchema,
    },
    {
      method: 'get',
      path: '/settings/period-lock-warning',
      summary: 'Period lock warnings',
      tag: 'Settings',
      query: dateRangeQuery,
    },

    ...crudSpecs('/invoice-templates', 'Settings', {
      resourceName: 'invoice templates',
      createSchema: createInvoiceTemplateSchema,
      updateSchema: updateInvoiceTemplateSchema,
    }).filter((s) => s.method !== 'delete'),

    {
      method: 'get',
      path: '/notifications',
      summary: 'List notifications',
      tag: 'Notifications',
      query: paginationQuery,
    },
    {
      method: 'patch',
      path: '/notifications/{id}/read',
      summary: 'Mark notification read',
      tag: 'Notifications',
      pathParams: idPathParams,
    },
    {
      method: 'post',
      path: '/notifications/read-all',
      summary: 'Mark all notifications read',
      tag: 'Notifications',
    },

    {
      method: 'get',
      path: '/approvals',
      summary: 'List approval requests',
      tag: 'Approvals',
      query: paginationQuery,
    },
    {
      method: 'post',
      path: '/approvals/{id}/approve',
      summary: 'Approve request',
      tag: 'Approvals',
      pathParams: idPathParams,
      body: reviewBodySchema,
    },
    {
      method: 'post',
      path: '/approvals/{id}/reject',
      summary: 'Reject request',
      tag: 'Approvals',
      pathParams: idPathParams,
      body: reviewBodySchema,
    },

    reportRouteSpec('/daily-sales', 'Daily sales'),
    reportRouteSpec('/stock-movement', 'Stock movement'),
    reportRouteSpec(
      '/fast-moving',
      'Fast moving products',
      dateRangeQuery.extend({
        limit: z.coerce.number().optional(),
        sortBy: z.enum(['quantity', 'value']).optional(),
      })
    ),
    reportRouteSpec('/expense-analysis', 'Expense analysis'),
    reportRouteSpec('/aging', 'Receivables aging (legacy)', asOfQuery),
    reportRouteSpec('/receivables-aging', 'Receivables aging', asOfQuery),
    reportRouteSpec('/payables-aging', 'Payables aging', asOfQuery),
    reportRouteSpec('/trial-balance', 'Trial balance'),
    reportRouteSpec('/profit-loss', 'Profit and loss'),
    reportRouteSpec('/balance-sheet', 'Balance sheet', z.object({ asOfDate: z.string().optional() })),
    reportRouteSpec(
      '/tax-collected',
      'Tax collected',
      dateRangeQuery.extend({ taxProfileId: z.string().uuid().optional() })
    ),
    reportRouteSpec(
      '/tax-paid',
      'Tax paid',
      dateRangeQuery.extend({ taxProfileId: z.string().uuid().optional() })
    ),
    reportRouteSpec('/tax-summary', 'Tax summary'),
    reportRouteSpec(
      '/dead-stock',
      'Dead stock',
      asOfQuery.extend({ daysWithoutSale: z.coerce.number().optional() })
    ),
    reportRouteSpec(
      '/slow-moving',
      'Slow moving',
      dateRangeQuery.extend({ limit: z.coerce.number().optional() })
    ),
    reportRouteSpec('/grn-invoice-reconciliation', 'GRN invoice reconciliation', asOfQuery),
    reportRouteSpec('/dashboard/kpis', 'Dashboard KPIs'),
    reportRouteSpec('/purchase-vs-sales', 'Purchase vs sales'),
    reportRouteSpec('/profit-by-product', 'Profit by product'),
    reportRouteSpec('/profit-by-customer', 'Profit by customer'),
    reportRouteSpec('/cash-flow', 'Cash flow'),

    { method: 'get', path: '/export/products', summary: 'Export products XLSX', tag: 'ImportExport' },
    { method: 'get', path: '/export/customers', summary: 'Export customers XLSX', tag: 'ImportExport' },
    {
      method: 'get',
      path: '/export/invoices',
      summary: 'Export invoices XLSX',
      tag: 'ImportExport',
      query: dateRangeQuery,
    },

    {
      method: 'get',
      path: '/import/products/template',
      summary: 'Product import template',
      tag: 'ImportExport',
    },
    {
      method: 'get',
      path: '/import/customers/template',
      summary: 'Customer import template',
      tag: 'ImportExport',
    },
    {
      method: 'get',
      path: '/import/opening-balances/template',
      summary: 'Opening balances template',
      tag: 'ImportExport',
    },
    { method: 'post', path: '/import/products', summary: 'Import products', tag: 'ImportExport' },
    { method: 'post', path: '/import/customers', summary: 'Import customers', tag: 'ImportExport' },
    {
      method: 'post',
      path: '/import/opening-balances',
      summary: 'Import opening balances',
      tag: 'ImportExport',
    },
  ];

  return buildPathsFromSpecs(specs);
}
