import { Product, ProductPrice } from '@tradeflow/db';
import { nullable } from '../../../shared/utils/serializeHelpers';

export function serializeProduct(p: Product, prices?: ProductPrice[]) {
  return {
    id: p.id,
    supplierId: p.supplierId,
    supplier: p.supplier ? { id: p.supplier.id, name: p.supplier.name } : undefined,
    categoryId: p.categoryId,
    sku: p.sku,
    barcode: p.barcode,
    name: p.name,
    unitId: p.unitId,
    costPrice: p.costPrice,
    sellingPrice: p.sellingPrice,
    batchTracked: p.batchTracked,
    expiryTracked: p.expiryTracked,
    costingMethod: nullable(p.costingMethod),
    minStock: p.minStock,
    reorderLevel: p.reorderLevel,
    manufacturerCode: nullable(p.manufacturerCode),
    shortName: nullable(p.shortName),
    genericName: nullable(p.genericName),
    packing: nullable(p.packing),
    hsCode: nullable(p.hsCode),
    retailPrice: p.retailPrice,
    purchaseDiscountPct: nullable(p.purchaseDiscountPct),
    salesDiscountPct: nullable(p.salesDiscountPct),
    purchaseSalesTaxPct: nullable(p.purchaseSalesTaxPct),
    purchaseWithholdingTaxPct: nullable(p.purchaseWithholdingTaxPct),
    purchaseFurtherTaxPct: nullable(p.purchaseFurtherTaxPct),
    salesSalesTaxPct: nullable(p.salesSalesTaxPct),
    salesWithholdingTaxPct: nullable(p.salesWithholdingTaxPct),
    salesFurtherTaxPct: nullable(p.salesFurtherTaxPct),
    saleType: nullable(p.saleType),
    saleRatePct: nullable(p.saleRatePct),
    sroSchedule: nullable(p.sroSchedule),
    sroItemSerial: nullable(p.sroItemSerial),
    isHerbal: p.isHerbal,
    isNarcotic: p.isNarcotic,
    isFridged: p.isFridged,
    isSurgical: p.isSurgical,
    staxBeforeDiscount: p.staxBeforeDiscount,
    staxOnRetail: p.staxOnRetail,
    staxOnBonusSale: p.staxOnBonusSale,
    staxOnBonusPurchase: p.staxOnBonusPurchase,
    tradePriceAllBatches: p.tradePriceAllBatches,
    autoPriceFromRetail: p.autoPriceFromRetail,
    printNetPriceOnInvoice: p.printNetPriceOnInvoice,
    isActive: p.isActive,
    createdAt: p.createdAt,
    updatedAt: p.updatedAt,
    deletedAt: p.deletedAt,
    prices:
      prices?.map((pp) => ({
        id: pp.id,
        priceLevelId: pp.priceLevelId,
        price: pp.price,
      })) ?? undefined,
  };
}
