import express from 'express';
import cors from 'cors';
import { healthRouter } from './routes/health';
import { authRouter } from './routes/auth';
import { auditRouter } from './routes/audit';
import { recycleBinRouter } from './routes/recycleBin';
import { productCategoriesRouter } from './routes/productCategories';
import { productsRouter } from './routes/products';
import { unitsRouter } from './routes/units';
import { priceLevelsRouter } from './routes/priceLevels';
import { customersRouter } from './routes/customers';
import { suppliersRouter } from './routes/suppliers';
import { warehousesRouter } from './routes/warehouses';
import { salespersonsRouter } from './routes/salespersons';
import { taxProfilesRouter } from './routes/taxProfiles';
import { paymentTermsRouter } from './routes/paymentTerms';
import { inventoryRouter } from './routes/inventory';
import { quotationsRouter } from './routes/quotations';
import { salesOrdersRouter } from './routes/salesOrders';
import { invoicesRouter } from './routes/invoices';
import { receiptsRouter } from './routes/receipts';
import { reportsRouter } from './routes/reports';
import { purchaseOrdersRouter } from './routes/purchaseOrders';
import { grnsRouter } from './routes/grns';
import { supplierInvoicesRouter } from './routes/supplierInvoices';
import { supplierPaymentsRouter } from './routes/supplierPayments';
import { accountsRouter } from './routes/accounts';
import { journalEntriesRouter } from './routes/journalEntries';
import { companySettingsRouter } from './routes/companySettings';
import { invoiceTemplatesRouter } from './routes/invoiceTemplates';
import { deliveryRoutesRouter } from './routes/deliveryRoutes';
import { deliveryRunsRouter } from './routes/deliveryRuns';
import { deliveryNotesRouter } from './routes/deliveryNotes';
import { importRouter } from './routes/import';
import { exportRouter } from './routes/export';

export const app = express();

app.use(cors({ origin: true, credentials: true }));
app.use(express.json());

app.use('/health', healthRouter);
app.use('/auth', authRouter);
app.use('/audit-logs', auditRouter);
app.use('/recycle-bin', recycleBinRouter);
app.use('/product-categories', productCategoriesRouter);
app.use('/products', productsRouter);
app.use('/units', unitsRouter);
app.use('/price-levels', priceLevelsRouter);
app.use('/customers', customersRouter);
app.use('/suppliers', suppliersRouter);
app.use('/warehouses', warehousesRouter);
app.use('/salespersons', salespersonsRouter);
app.use('/tax-profiles', taxProfilesRouter);
app.use('/payment-terms', paymentTermsRouter);
app.use('/inventory', inventoryRouter);
app.use('/quotations', quotationsRouter);
app.use('/sales-orders', salesOrdersRouter);
app.use('/invoices', invoicesRouter);
app.use('/receipts', receiptsRouter);
app.use('/reports', reportsRouter);
app.use('/purchase-orders', purchaseOrdersRouter);
app.use('/grns', grnsRouter);
app.use('/supplier-invoices', supplierInvoicesRouter);
app.use('/supplier-payments', supplierPaymentsRouter);
app.use('/accounts', accountsRouter);
app.use('/journal-entries', journalEntriesRouter);
app.use('/settings', companySettingsRouter);
app.use('/invoice-templates', invoiceTemplatesRouter);
app.use('/delivery-routes', deliveryRoutesRouter);
app.use('/delivery-runs', deliveryRunsRouter);
app.use('/delivery-notes', deliveryNotesRouter);
app.use('/import', importRouter);
app.use('/export', exportRouter);
